[package]
name = "arbiter-gui"
description = "A GUI framework library for everything between an App and the screen."
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "gui"

[dependencies]
bytemuck.workspace = true
fontique.workspace = true
harfrust.workspace = true
pollster.workspace = true
resvg.workspace = true
skrifa.workspace = true
thiserror.workspace = true
unicode-script.workspace = true
wgpu.workspace = true
winit.workspace = true
zeno.workspace = true

[lints]
workspace = true
