[package]
name = "arbiter-pack"
description = "Unpacking a disc into files, and turning documents into a build target (packing)."
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "pack"

[dependencies]
arbiter-diag.workspace = true
arbiter-formats.workspace = true
nod.workspace = true
thiserror.workspace = true
xxhash-rust.workspace = true


[lints]
workspace = true
