[package]
name = "arbiter"
description = "An editor for viewing, editing, and building mods for GameCube and Wii games."
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arbiter-diag.workspace = true
arbiter-app.workspace = true
arbiter-project.workspace = true
clap.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["fmt", "ansi"] }

[lints]
workspace = true
